ARG BASE_IMAGE=nvidia/cudagl:10.0-devel-ubuntu18.04
FROM $BASE_IMAGE

# basic dependencies
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends \
	sudo \
	libglu1-mesa-dev \
	xdg-user-dirs \
	pulseaudio \
	x11-xserver-utils

RUN sudo apt-get update \
    && sudo apt-get install -y build-essential \
    && sudo apt-get install -y wget \
    && sudo apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y



# install the dependencies that allow us to install our specific version of python
RUN sudo apt-get update
RUN sudo apt update
RUN sudo apt install build-essential zlib1g-dev \
    libncurses5-dev libgdbm-dev libnss3-dev \
    libssl-dev libreadline-dev libffi-dev curl software-properties-common -y



# install python 3.9.16
RUN cd /usr/src
RUN wget https://www.python.org/ftp/python/3.9.16/Python-3.9.16.tar.xz
RUN tar -xf Python-3.9.16.tar.xz
RUN cd Python-3.9.16 \
    && ./configure \
    && sudo make altinstall

RUN python3.9 -m pip install --upgrade pip


# install airsim specific libraries and dependencies
RUN pip3 install setuptools wheel
RUN pip3 install torch torchrl tqdm msgpack-rpc-python airsim neat-python tornado scipy pyyaml keyboard path

RUN adduser --force-badname --disabled-password --gecos '' --shell /bin/bash airsim_user && \
	echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
	adduser airsim_user sudo && \
	adduser airsim_user audio && \
	adduser airsim_user video

USER airsim_user
WORKDIR /home/airsim_user

RUN mkdir -p /home/airsim_user/Documents/AirSim
COPY settings.json /home/airsim_user/Documents/AirSim

RUN sudo chown -R airsim_user /home/airsim_user


# install marco polo/ drone code onto the docker image and install all of its dependencies
RUN mkdir ~/Downloads/Marco_Polo_Drone
ADD Marco_Polo_Drone/* ~/Downloads/Marco_Polo_Drone
RUN ~/Downloads/Marco_Polo_Drone/setup_MP.sh



ENTRYPOINT ls